package servidorusuarios_sop_corba.GestionPacientesPackage;


/**
* servidorusuarios_sop_corba/GestionPacientesPackage/pacienteDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* domingo 10 de diciembre de 2023 12:49:19 AM COT
*/

public final class pacienteDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int identificacion = (int)0;
  public String nombres = null;
  public String apellidos = null;
  public float edad = (float)0;

  public pacienteDTO ()
  {
  } // ctor

  public pacienteDTO (int _identificacion, String _nombres, String _apellidos, float _edad)
  {
    identificacion = _identificacion;
    nombres = _nombres;
    apellidos = _apellidos;
    edad = _edad;
  } // ctor

} // class pacienteDTO
