package servidorusuarios_sop_corba.GestionPacientesPackage;


/**
* servidorusuarios_sop_corba/GestionPacientesPackage/pacienteDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* domingo 10 de diciembre de 2023 12:49:19 AM COT
*/

abstract public class pacienteDTOHelper
{
  private static String  _id = "IDL:servidorusuarios_sop_corba/GestionPacientes/pacienteDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "identificacion",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "nombres",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "apellidos",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[3] = new org.omg.CORBA.StructMember (
            "edad",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTOHelper.id (), "pacienteDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTO value = new servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTO ();
    value.identificacion = istream.read_long ();
    value.nombres = istream.read_string ();
    value.apellidos = istream.read_string ();
    value.edad = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTO value)
  {
    ostream.write_long (value.identificacion);
    ostream.write_string (value.nombres);
    ostream.write_string (value.apellidos);
    ostream.write_float (value.edad);
  }

}
