package servidorusuarios_sop_corba.GestionPacientesPackage;

/**
* servidorusuarios_sop_corba/GestionPacientesPackage/pacienteDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* domingo 10 de diciembre de 2023 12:49:19 AM COT
*/

public final class pacienteDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTO value = null;

  public pacienteDTOHolder ()
  {
  }

  public pacienteDTOHolder (servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTOHelper.type ();
  }

}
