package servidorusuarios_sop_corba;


/**
* servidorusuarios_sop_corba/GestionPacientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* domingo 10 de diciembre de 2023 12:49:19 AM COT
*/

public interface GestionPacientesOperations 
{
  boolean registrarPaciente (servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTO objPaciente);
  servidorusuarios_sop_corba.GestionPacientesPackage.pacienteDTO buscarPaciente (int noIdentificacion);
} // interface GestionPacientesOperations
