package servidorusuarios_sop_corba;

/**
* servidorusuarios_sop_corba/GestionPacientesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* domingo 10 de diciembre de 2023 12:49:19 AM COT
*/

public final class GestionPacientesHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorusuarios_sop_corba.GestionPacientes value = null;

  public GestionPacientesHolder ()
  {
  }

  public GestionPacientesHolder (servidorusuarios_sop_corba.GestionPacientes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorusuarios_sop_corba.GestionPacientesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorusuarios_sop_corba.GestionPacientesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorusuarios_sop_corba.GestionPacientesHelper.type ();
  }

}
